name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - uses: actions/checkout@v4

      # Step 2: Set up Node.js (ensure the correct Node version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Ensure it matches your local Node version

      # Step 3: Install dependencies (this will install react-scripts and other dependencies)
      - name: Install dependencies
        run: npm install

      # Step 4: Build the project (react-scripts will be found now)
      - name: Build project
        run: npm run build

      # Step 5: Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MEMOIRCRAFT_6BE65 }}
          channelId: live
          projectId: memoircraft-6be65
